name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Build
      run: |
        cd AGI-PDM
        dotnet publish -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true
    
    - name: Package Release
      shell: pwsh
      run: |
        # Create release directory structure
        New-Item -ItemType Directory -Path release -Force
        
        # Copy ONLY the executable
        Copy-Item "AGI-PDM\bin\Release\net8.0\win-x64\publish\AGI-PDM.exe" "release\"
        
        # Create a sample config.json (users will modify this)
        Copy-Item "AGI-PDM\config.json" "release\config.sample.json"
        
        # Create a minimal README for the release
        @"
        AGI PDM Migrator ${{ github.ref_name }}
        =====================================
        
        Quick Start
        -----------
        1. Copy config.sample.json to config.json
        2. Edit config.json with your server details
        3. Run AGI-PDM.exe as Administrator
        
        For automated deployment, download the bootstrap script from:
        https://github.com/jwraynor/AGI.PDM-Migrator/blob/main/scripts/Install-AGIPDMMigrator.ps1
        
        Documentation
        -------------
        Full documentation available at:
        https://github.com/jwraynor/AGI.PDM-Migrator/tree/main/docs
        
        Requirements
        ------------
        - Windows 10/11 or Windows Server 2016+
        - .NET 8.0 Runtime
        - SolidWorks PDM Client installed
        - Administrator privileges
        "@ | Out-File -FilePath "release\README.txt" -Encoding UTF8
        
        # Create the zip file
        $zipName = "AGI-PDM-Migrator-${{ github.ref_name }}.zip"
        Compress-Archive -Path "release\*" -DestinationPath $zipName
        
        # Also create a standalone exe download
        Copy-Item "AGI-PDM\bin\Release\net8.0\win-x64\publish\AGI-PDM.exe" "AGI-PDM-${{ github.ref_name }}.exe"
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          AGI-PDM-Migrator-${{ github.ref_name }}.zip
          AGI-PDM-${{ github.ref_name }}.exe
        name: AGI PDM Migrator ${{ github.ref_name }}
        body: |
          ## AGI PDM Migrator ${{ github.ref_name }}
          
          ### Downloads
          
          - **AGI-PDM-Migrator-${{ github.ref_name }}.zip** - Full package with sample config
          - **AGI-PDM-${{ github.ref_name }}.exe** - Standalone executable only
          
          ### Automated Deployment (Recommended)
          
          Use the bootstrap script to automatically download and run:
          ```powershell
          # Download bootstrap script
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/jwraynor/AGI.PDM-Migrator/main/scripts/Install-AGIPDMMigrator.ps1" -OutFile "Install-AGIPDMMigrator.ps1"
          
          # Run it
          .\Install-AGIPDMMigrator.ps1
          ```
          
          ### Manual Installation
          
          1. Download `AGI-PDM-Migrator-${{ github.ref_name }}.zip`
          2. Extract to a folder
          3. Copy `config.sample.json` to `config.json`
          4. Edit `config.json` with your server details
          5. Run `AGI-PDM.exe` as Administrator
          
          ### Requirements
          
          - Windows 10/11 or Windows Server 2016+
          - [.NET 8.0 Runtime](https://dotnet.microsoft.com/download/dotnet/8.0)
          - SolidWorks PDM Client installed
          - Administrator privileges
          
          ### Documentation
          
          - [Configuration Guide](https://github.com/jwraynor/AGI.PDM-Migrator/blob/main/docs/Configuration.md)
          - [Usage Guide](https://github.com/jwraynor/AGI.PDM-Migrator/blob/main/docs/Usage.md)
          - [Release Process](https://github.com/jwraynor/AGI.PDM-Migrator/blob/main/docs/Release-Process.md)
          
          ### What's New
          
          Initial release with:
          - Automated PDM vault migration
          - Autonomous mode for RMM deployment
          - Pre-flight checks
          - Registry backup
          - Detailed logging
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}